name: Deploy AI Ad Manager

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ai-ad-manager --source .
